/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
)

// checks if the ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions{}

// ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions struct for ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions
type ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions struct {
	Appid *string `json:"appid,omitempty"`
	CredProps *bool `json:"credProps,omitempty"`
	HmacCreateSecret *bool `json:"hmacCreateSecret,omitempty"`
}

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions() *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions {
	this := ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions{}
	return &this
}

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensionsWithDefaults instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensionsWithDefaults() *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions {
	this := ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions{}
	return &this
}

// GetAppid returns the Appid field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) GetAppid() string {
	if o == nil || IsNil(o.Appid) {
		var ret string
		return ret
	}
	return *o.Appid
}

// GetAppidOk returns a tuple with the Appid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) GetAppidOk() (*string, bool) {
	if o == nil || IsNil(o.Appid) {
		return nil, false
	}
	return o.Appid, true
}

// HasAppid returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) HasAppid() bool {
	if o != nil && !IsNil(o.Appid) {
		return true
	}

	return false
}

// SetAppid gets a reference to the given string and assigns it to the Appid field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) SetAppid(v string) {
	o.Appid = &v
}

// GetCredProps returns the CredProps field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) GetCredProps() bool {
	if o == nil || IsNil(o.CredProps) {
		var ret bool
		return ret
	}
	return *o.CredProps
}

// GetCredPropsOk returns a tuple with the CredProps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) GetCredPropsOk() (*bool, bool) {
	if o == nil || IsNil(o.CredProps) {
		return nil, false
	}
	return o.CredProps, true
}

// HasCredProps returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) HasCredProps() bool {
	if o != nil && !IsNil(o.CredProps) {
		return true
	}

	return false
}

// SetCredProps gets a reference to the given bool and assigns it to the CredProps field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) SetCredProps(v bool) {
	o.CredProps = &v
}

// GetHmacCreateSecret returns the HmacCreateSecret field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) GetHmacCreateSecret() bool {
	if o == nil || IsNil(o.HmacCreateSecret) {
		var ret bool
		return ret
	}
	return *o.HmacCreateSecret
}

// GetHmacCreateSecretOk returns a tuple with the HmacCreateSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) GetHmacCreateSecretOk() (*bool, bool) {
	if o == nil || IsNil(o.HmacCreateSecret) {
		return nil, false
	}
	return o.HmacCreateSecret, true
}

// HasHmacCreateSecret returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) HasHmacCreateSecret() bool {
	if o != nil && !IsNil(o.HmacCreateSecret) {
		return true
	}

	return false
}

// SetHmacCreateSecret gets a reference to the given bool and assigns it to the HmacCreateSecret field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) SetHmacCreateSecret(v bool) {
	o.HmacCreateSecret = &v
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Appid) {
		toSerialize["appid"] = o.Appid
	}
	if !IsNil(o.CredProps) {
		toSerialize["credProps"] = o.CredProps
	}
	if !IsNil(o.HmacCreateSecret) {
		toSerialize["hmacCreateSecret"] = o.HmacCreateSecret
	}
	return toSerialize, nil
}

type NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions struct {
	value *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions
	isSet bool
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) Get() *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions {
	return v.value
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) Set(val *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions(val *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions {
	return &NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions{value: val, isSet: true}
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

