/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"fmt"
)

// VerifyVerificationCodeRequest - struct for VerifyVerificationCodeRequest
type VerifyVerificationCodeRequest struct {
	ApiInteractionPutRequestIdentifierOneOf3 *ApiInteractionPutRequestIdentifierOneOf3
	ApiInteractionPutRequestIdentifierOneOf4 *ApiInteractionPutRequestIdentifierOneOf4
}

// ApiInteractionPutRequestIdentifierOneOf3AsVerifyVerificationCodeRequest is a convenience function that returns ApiInteractionPutRequestIdentifierOneOf3 wrapped in VerifyVerificationCodeRequest
func ApiInteractionPutRequestIdentifierOneOf3AsVerifyVerificationCodeRequest(v *ApiInteractionPutRequestIdentifierOneOf3) VerifyVerificationCodeRequest {
	return VerifyVerificationCodeRequest{
		ApiInteractionPutRequestIdentifierOneOf3: v,
	}
}

// ApiInteractionPutRequestIdentifierOneOf4AsVerifyVerificationCodeRequest is a convenience function that returns ApiInteractionPutRequestIdentifierOneOf4 wrapped in VerifyVerificationCodeRequest
func ApiInteractionPutRequestIdentifierOneOf4AsVerifyVerificationCodeRequest(v *ApiInteractionPutRequestIdentifierOneOf4) VerifyVerificationCodeRequest {
	return VerifyVerificationCodeRequest{
		ApiInteractionPutRequestIdentifierOneOf4: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *VerifyVerificationCodeRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ApiInteractionPutRequestIdentifierOneOf3
	err = newStrictDecoder(data).Decode(&dst.ApiInteractionPutRequestIdentifierOneOf3)
	if err == nil {
		jsonApiInteractionPutRequestIdentifierOneOf3, _ := json.Marshal(dst.ApiInteractionPutRequestIdentifierOneOf3)
		if string(jsonApiInteractionPutRequestIdentifierOneOf3) == "{}" { // empty struct
			dst.ApiInteractionPutRequestIdentifierOneOf3 = nil
		} else {
			match++
		}
	} else {
		dst.ApiInteractionPutRequestIdentifierOneOf3 = nil
	}

	// try to unmarshal data into ApiInteractionPutRequestIdentifierOneOf4
	err = newStrictDecoder(data).Decode(&dst.ApiInteractionPutRequestIdentifierOneOf4)
	if err == nil {
		jsonApiInteractionPutRequestIdentifierOneOf4, _ := json.Marshal(dst.ApiInteractionPutRequestIdentifierOneOf4)
		if string(jsonApiInteractionPutRequestIdentifierOneOf4) == "{}" { // empty struct
			dst.ApiInteractionPutRequestIdentifierOneOf4 = nil
		} else {
			match++
		}
	} else {
		dst.ApiInteractionPutRequestIdentifierOneOf4 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ApiInteractionPutRequestIdentifierOneOf3 = nil
		dst.ApiInteractionPutRequestIdentifierOneOf4 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(VerifyVerificationCodeRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(VerifyVerificationCodeRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src VerifyVerificationCodeRequest) MarshalJSON() ([]byte, error) {
	if src.ApiInteractionPutRequestIdentifierOneOf3 != nil {
		return json.Marshal(&src.ApiInteractionPutRequestIdentifierOneOf3)
	}

	if src.ApiInteractionPutRequestIdentifierOneOf4 != nil {
		return json.Marshal(&src.ApiInteractionPutRequestIdentifierOneOf4)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *VerifyVerificationCodeRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ApiInteractionPutRequestIdentifierOneOf3 != nil {
		return obj.ApiInteractionPutRequestIdentifierOneOf3
	}

	if obj.ApiInteractionPutRequestIdentifierOneOf4 != nil {
		return obj.ApiInteractionPutRequestIdentifierOneOf4
	}

	// all schemas are nil
	return nil
}

type NullableVerifyVerificationCodeRequest struct {
	value *VerifyVerificationCodeRequest
	isSet bool
}

func (v NullableVerifyVerificationCodeRequest) Get() *VerifyVerificationCodeRequest {
	return v.value
}

func (v *NullableVerifyVerificationCodeRequest) Set(val *VerifyVerificationCodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyVerificationCodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyVerificationCodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyVerificationCodeRequest(val *VerifyVerificationCodeRequest) *NullableVerifyVerificationCodeRequest {
	return &NullableVerifyVerificationCodeRequest{value: val, isSet: true}
}

func (v NullableVerifyVerificationCodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyVerificationCodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


