/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateHook200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateHook200Response{}

// UpdateHook200Response struct for UpdateHook200Response
type UpdateHook200Response struct {
	TenantId string `json:"tenantId"`
	Id string `json:"id"`
	Name string `json:"name"`
	Event NullableString `json:"event"`
	Events []string `json:"events"`
	Config ListHooks200ResponseInnerConfig `json:"config"`
	SigningKey string `json:"signingKey"`
	Enabled bool `json:"enabled"`
	CreatedAt float32 `json:"createdAt"`
}

type _UpdateHook200Response UpdateHook200Response

// NewUpdateHook200Response instantiates a new UpdateHook200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateHook200Response(tenantId string, id string, name string, event NullableString, events []string, config ListHooks200ResponseInnerConfig, signingKey string, enabled bool, createdAt float32) *UpdateHook200Response {
	this := UpdateHook200Response{}
	this.TenantId = tenantId
	this.Id = id
	this.Name = name
	this.Event = event
	this.Events = events
	this.Config = config
	this.SigningKey = signingKey
	this.Enabled = enabled
	this.CreatedAt = createdAt
	return &this
}

// NewUpdateHook200ResponseWithDefaults instantiates a new UpdateHook200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateHook200ResponseWithDefaults() *UpdateHook200Response {
	this := UpdateHook200Response{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *UpdateHook200Response) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *UpdateHook200Response) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *UpdateHook200Response) SetTenantId(v string) {
	o.TenantId = v
}

// GetId returns the Id field value
func (o *UpdateHook200Response) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateHook200Response) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateHook200Response) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *UpdateHook200Response) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateHook200Response) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateHook200Response) SetName(v string) {
	o.Name = v
}

// GetEvent returns the Event field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UpdateHook200Response) GetEvent() string {
	if o == nil || o.Event.Get() == nil {
		var ret string
		return ret
	}

	return *o.Event.Get()
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateHook200Response) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Event.Get(), o.Event.IsSet()
}

// SetEvent sets field value
func (o *UpdateHook200Response) SetEvent(v string) {
	o.Event.Set(&v)
}

// GetEvents returns the Events field value
func (o *UpdateHook200Response) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *UpdateHook200Response) GetEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *UpdateHook200Response) SetEvents(v []string) {
	o.Events = v
}

// GetConfig returns the Config field value
func (o *UpdateHook200Response) GetConfig() ListHooks200ResponseInnerConfig {
	if o == nil {
		var ret ListHooks200ResponseInnerConfig
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *UpdateHook200Response) GetConfigOk() (*ListHooks200ResponseInnerConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *UpdateHook200Response) SetConfig(v ListHooks200ResponseInnerConfig) {
	o.Config = v
}

// GetSigningKey returns the SigningKey field value
func (o *UpdateHook200Response) GetSigningKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SigningKey
}

// GetSigningKeyOk returns a tuple with the SigningKey field value
// and a boolean to check if the value has been set.
func (o *UpdateHook200Response) GetSigningKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SigningKey, true
}

// SetSigningKey sets field value
func (o *UpdateHook200Response) SetSigningKey(v string) {
	o.SigningKey = v
}

// GetEnabled returns the Enabled field value
func (o *UpdateHook200Response) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *UpdateHook200Response) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *UpdateHook200Response) SetEnabled(v bool) {
	o.Enabled = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *UpdateHook200Response) GetCreatedAt() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UpdateHook200Response) GetCreatedAtOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UpdateHook200Response) SetCreatedAt(v float32) {
	o.CreatedAt = v
}

func (o UpdateHook200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateHook200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["event"] = o.Event.Get()
	toSerialize["events"] = o.Events
	toSerialize["config"] = o.Config
	toSerialize["signingKey"] = o.SigningKey
	toSerialize["enabled"] = o.Enabled
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *UpdateHook200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"id",
		"name",
		"event",
		"events",
		"config",
		"signingKey",
		"enabled",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateHook200Response := _UpdateHook200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateHook200Response)

	if err != nil {
		return err
	}

	*o = UpdateHook200Response(varUpdateHook200Response)

	return err
}

type NullableUpdateHook200Response struct {
	value *UpdateHook200Response
	isSet bool
}

func (v NullableUpdateHook200Response) Get() *UpdateHook200Response {
	return v.value
}

func (v *NullableUpdateHook200Response) Set(val *UpdateHook200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateHook200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateHook200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateHook200Response(val *UpdateHook200Response) *NullableUpdateHook200Response {
	return &NullableUpdateHook200Response{value: val, isSet: true}
}

func (v NullableUpdateHook200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateHook200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

