/*
Logto API references

Testing SwaggerJsonAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package logto

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	logto "github.com/mostafa/go-api-client"
)

func Test_logto_SwaggerJsonAPIService(t *testing.T) {

	configuration := logto.NewConfiguration()
	apiClient := logto.NewAPIClient(configuration)

	t.Run("Test SwaggerJsonAPIService GetSwaggerJson", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.SwaggerJsonAPI.GetSwaggerJson(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
