/*
Logto API references

Testing WellKnownAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package logto

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	logto "github.com/mostafa/go-api-client"
)

func Test_logto_WellKnownAPIService(t *testing.T) {

	configuration := logto.NewConfiguration()
	apiClient := logto.NewAPIClient(configuration)

	t.Run("Test WellKnownAPIService GetSignInExperienceConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WellKnownAPI.GetSignInExperienceConfig(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WellKnownAPIService GetSignInExperiencePhrases", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WellKnownAPI.GetSignInExperiencePhrases(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
