/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiInteractionVerificationVerificationCodePostRequestOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionVerificationVerificationCodePostRequestOneOf1{}

// ApiInteractionVerificationVerificationCodePostRequestOneOf1 struct for ApiInteractionVerificationVerificationCodePostRequestOneOf1
type ApiInteractionVerificationVerificationCodePostRequestOneOf1 struct {
	Phone string `json:"phone"`
}

type _ApiInteractionVerificationVerificationCodePostRequestOneOf1 ApiInteractionVerificationVerificationCodePostRequestOneOf1

// NewApiInteractionVerificationVerificationCodePostRequestOneOf1 instantiates a new ApiInteractionVerificationVerificationCodePostRequestOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionVerificationVerificationCodePostRequestOneOf1(phone string) *ApiInteractionVerificationVerificationCodePostRequestOneOf1 {
	this := ApiInteractionVerificationVerificationCodePostRequestOneOf1{}
	this.Phone = phone
	return &this
}

// NewApiInteractionVerificationVerificationCodePostRequestOneOf1WithDefaults instantiates a new ApiInteractionVerificationVerificationCodePostRequestOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionVerificationVerificationCodePostRequestOneOf1WithDefaults() *ApiInteractionVerificationVerificationCodePostRequestOneOf1 {
	this := ApiInteractionVerificationVerificationCodePostRequestOneOf1{}
	return &this
}

// GetPhone returns the Phone field value
func (o *ApiInteractionVerificationVerificationCodePostRequestOneOf1) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationVerificationCodePostRequestOneOf1) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *ApiInteractionVerificationVerificationCodePostRequestOneOf1) SetPhone(v string) {
	o.Phone = v
}

func (o ApiInteractionVerificationVerificationCodePostRequestOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionVerificationVerificationCodePostRequestOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phone"] = o.Phone
	return toSerialize, nil
}

func (o *ApiInteractionVerificationVerificationCodePostRequestOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiInteractionVerificationVerificationCodePostRequestOneOf1 := _ApiInteractionVerificationVerificationCodePostRequestOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiInteractionVerificationVerificationCodePostRequestOneOf1)

	if err != nil {
		return err
	}

	*o = ApiInteractionVerificationVerificationCodePostRequestOneOf1(varApiInteractionVerificationVerificationCodePostRequestOneOf1)

	return err
}

type NullableApiInteractionVerificationVerificationCodePostRequestOneOf1 struct {
	value *ApiInteractionVerificationVerificationCodePostRequestOneOf1
	isSet bool
}

func (v NullableApiInteractionVerificationVerificationCodePostRequestOneOf1) Get() *ApiInteractionVerificationVerificationCodePostRequestOneOf1 {
	return v.value
}

func (v *NullableApiInteractionVerificationVerificationCodePostRequestOneOf1) Set(val *ApiInteractionVerificationVerificationCodePostRequestOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionVerificationVerificationCodePostRequestOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionVerificationVerificationCodePostRequestOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionVerificationVerificationCodePostRequestOneOf1(val *ApiInteractionVerificationVerificationCodePostRequestOneOf1) *NullableApiInteractionVerificationVerificationCodePostRequestOneOf1 {
	return &NullableApiInteractionVerificationVerificationCodePostRequestOneOf1{value: val, isSet: true}
}

func (v NullableApiInteractionVerificationVerificationCodePostRequestOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionVerificationVerificationCodePostRequestOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

