/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiInteractionPutRequestIdentifierOneOf6 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionPutRequestIdentifierOneOf6{}

// ApiInteractionPutRequestIdentifierOneOf6 struct for ApiInteractionPutRequestIdentifierOneOf6
type ApiInteractionPutRequestIdentifierOneOf6 struct {
	ConnectorId string `json:"connectorId"`
	Email string `json:"email"`
}

type _ApiInteractionPutRequestIdentifierOneOf6 ApiInteractionPutRequestIdentifierOneOf6

// NewApiInteractionPutRequestIdentifierOneOf6 instantiates a new ApiInteractionPutRequestIdentifierOneOf6 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionPutRequestIdentifierOneOf6(connectorId string, email string) *ApiInteractionPutRequestIdentifierOneOf6 {
	this := ApiInteractionPutRequestIdentifierOneOf6{}
	this.ConnectorId = connectorId
	this.Email = email
	return &this
}

// NewApiInteractionPutRequestIdentifierOneOf6WithDefaults instantiates a new ApiInteractionPutRequestIdentifierOneOf6 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionPutRequestIdentifierOneOf6WithDefaults() *ApiInteractionPutRequestIdentifierOneOf6 {
	this := ApiInteractionPutRequestIdentifierOneOf6{}
	return &this
}

// GetConnectorId returns the ConnectorId field value
func (o *ApiInteractionPutRequestIdentifierOneOf6) GetConnectorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectorId
}

// GetConnectorIdOk returns a tuple with the ConnectorId field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionPutRequestIdentifierOneOf6) GetConnectorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectorId, true
}

// SetConnectorId sets field value
func (o *ApiInteractionPutRequestIdentifierOneOf6) SetConnectorId(v string) {
	o.ConnectorId = v
}

// GetEmail returns the Email field value
func (o *ApiInteractionPutRequestIdentifierOneOf6) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionPutRequestIdentifierOneOf6) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ApiInteractionPutRequestIdentifierOneOf6) SetEmail(v string) {
	o.Email = v
}

func (o ApiInteractionPutRequestIdentifierOneOf6) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionPutRequestIdentifierOneOf6) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connectorId"] = o.ConnectorId
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *ApiInteractionPutRequestIdentifierOneOf6) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connectorId",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiInteractionPutRequestIdentifierOneOf6 := _ApiInteractionPutRequestIdentifierOneOf6{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiInteractionPutRequestIdentifierOneOf6)

	if err != nil {
		return err
	}

	*o = ApiInteractionPutRequestIdentifierOneOf6(varApiInteractionPutRequestIdentifierOneOf6)

	return err
}

type NullableApiInteractionPutRequestIdentifierOneOf6 struct {
	value *ApiInteractionPutRequestIdentifierOneOf6
	isSet bool
}

func (v NullableApiInteractionPutRequestIdentifierOneOf6) Get() *ApiInteractionPutRequestIdentifierOneOf6 {
	return v.value
}

func (v *NullableApiInteractionPutRequestIdentifierOneOf6) Set(val *ApiInteractionPutRequestIdentifierOneOf6) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionPutRequestIdentifierOneOf6) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionPutRequestIdentifierOneOf6) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionPutRequestIdentifierOneOf6(val *ApiInteractionPutRequestIdentifierOneOf6) *NullableApiInteractionPutRequestIdentifierOneOf6 {
	return &NullableApiInteractionPutRequestIdentifierOneOf6{value: val, isSet: true}
}

func (v NullableApiInteractionPutRequestIdentifierOneOf6) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionPutRequestIdentifierOneOf6) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

