/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner{}

// ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner struct for ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner
type ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner struct {
	Type string `json:"type"`
	Alg float32 `json:"alg"`
}

type _ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner(type_ string, alg float32) *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner {
	this := ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner{}
	this.Type = type_
	this.Alg = alg
	return &this
}

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInnerWithDefaults instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInnerWithDefaults() *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner {
	this := ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner{}
	return &this
}

// GetType returns the Type field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) SetType(v string) {
	o.Type = v
}

// GetAlg returns the Alg field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) GetAlg() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Alg
}

// GetAlgOk returns a tuple with the Alg field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) GetAlgOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alg, true
}

// SetAlg sets field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) SetAlg(v float32) {
	o.Alg = v
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["alg"] = o.Alg
	return toSerialize, nil
}

func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"alg",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner := _ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner)

	if err != nil {
		return err
	}

	*o = ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner(varApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner)

	return err
}

type NullableApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner struct {
	value *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner
	isSet bool
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) Get() *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner {
	return v.value
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) Set(val *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner(val *ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner {
	return &NullableApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner{value: val, isSet: true}
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

