/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiInteractionVerificationWebauthnRegistrationPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionVerificationWebauthnRegistrationPost200Response{}

// ApiInteractionVerificationWebauthnRegistrationPost200Response struct for ApiInteractionVerificationWebauthnRegistrationPost200Response
type ApiInteractionVerificationWebauthnRegistrationPost200Response struct {
	Rp ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp `json:"rp"`
	User ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser `json:"user"`
	Challenge string `json:"challenge"`
	PubKeyCredParams []ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner `json:"pubKeyCredParams"`
	Timeout *float32 `json:"timeout,omitempty"`
	ExcludeCredentials []ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner `json:"excludeCredentials,omitempty"`
	AuthenticatorSelection *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection `json:"authenticatorSelection,omitempty"`
	Attestation *string `json:"attestation,omitempty"`
	Extensions *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions `json:"extensions,omitempty"`
}

type _ApiInteractionVerificationWebauthnRegistrationPost200Response ApiInteractionVerificationWebauthnRegistrationPost200Response

// NewApiInteractionVerificationWebauthnRegistrationPost200Response instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionVerificationWebauthnRegistrationPost200Response(rp ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp, user ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser, challenge string, pubKeyCredParams []ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) *ApiInteractionVerificationWebauthnRegistrationPost200Response {
	this := ApiInteractionVerificationWebauthnRegistrationPost200Response{}
	this.Rp = rp
	this.User = user
	this.Challenge = challenge
	this.PubKeyCredParams = pubKeyCredParams
	return &this
}

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponseWithDefaults instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponseWithDefaults() *ApiInteractionVerificationWebauthnRegistrationPost200Response {
	this := ApiInteractionVerificationWebauthnRegistrationPost200Response{}
	return &this
}

// GetRp returns the Rp field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetRp() ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp {
	if o == nil {
		var ret ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp
		return ret
	}

	return o.Rp
}

// GetRpOk returns a tuple with the Rp field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetRpOk() (*ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rp, true
}

// SetRp sets field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) SetRp(v ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) {
	o.Rp = v
}

// GetUser returns the User field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetUser() ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser {
	if o == nil {
		var ret ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetUserOk() (*ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) SetUser(v ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) {
	o.User = v
}

// GetChallenge returns the Challenge field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetChallenge() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Challenge
}

// GetChallengeOk returns a tuple with the Challenge field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetChallengeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Challenge, true
}

// SetChallenge sets field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) SetChallenge(v string) {
	o.Challenge = v
}

// GetPubKeyCredParams returns the PubKeyCredParams field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetPubKeyCredParams() []ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner {
	if o == nil {
		var ret []ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner
		return ret
	}

	return o.PubKeyCredParams
}

// GetPubKeyCredParamsOk returns a tuple with the PubKeyCredParams field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetPubKeyCredParamsOk() ([]ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.PubKeyCredParams, true
}

// SetPubKeyCredParams sets field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) SetPubKeyCredParams(v []ApiInteractionVerificationWebauthnRegistrationPost200ResponsePubKeyCredParamsInner) {
	o.PubKeyCredParams = v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetTimeout() float32 {
	if o == nil || IsNil(o.Timeout) {
		var ret float32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetTimeoutOk() (*float32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given float32 and assigns it to the Timeout field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) SetTimeout(v float32) {
	o.Timeout = &v
}

// GetExcludeCredentials returns the ExcludeCredentials field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetExcludeCredentials() []ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner {
	if o == nil || IsNil(o.ExcludeCredentials) {
		var ret []ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner
		return ret
	}
	return o.ExcludeCredentials
}

// GetExcludeCredentialsOk returns a tuple with the ExcludeCredentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetExcludeCredentialsOk() ([]ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner, bool) {
	if o == nil || IsNil(o.ExcludeCredentials) {
		return nil, false
	}
	return o.ExcludeCredentials, true
}

// HasExcludeCredentials returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) HasExcludeCredentials() bool {
	if o != nil && !IsNil(o.ExcludeCredentials) {
		return true
	}

	return false
}

// SetExcludeCredentials gets a reference to the given []ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner and assigns it to the ExcludeCredentials field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) SetExcludeCredentials(v []ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) {
	o.ExcludeCredentials = v
}

// GetAuthenticatorSelection returns the AuthenticatorSelection field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetAuthenticatorSelection() ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection {
	if o == nil || IsNil(o.AuthenticatorSelection) {
		var ret ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection
		return ret
	}
	return *o.AuthenticatorSelection
}

// GetAuthenticatorSelectionOk returns a tuple with the AuthenticatorSelection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetAuthenticatorSelectionOk() (*ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection, bool) {
	if o == nil || IsNil(o.AuthenticatorSelection) {
		return nil, false
	}
	return o.AuthenticatorSelection, true
}

// HasAuthenticatorSelection returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) HasAuthenticatorSelection() bool {
	if o != nil && !IsNil(o.AuthenticatorSelection) {
		return true
	}

	return false
}

// SetAuthenticatorSelection gets a reference to the given ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection and assigns it to the AuthenticatorSelection field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) SetAuthenticatorSelection(v ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) {
	o.AuthenticatorSelection = &v
}

// GetAttestation returns the Attestation field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetAttestation() string {
	if o == nil || IsNil(o.Attestation) {
		var ret string
		return ret
	}
	return *o.Attestation
}

// GetAttestationOk returns a tuple with the Attestation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetAttestationOk() (*string, bool) {
	if o == nil || IsNil(o.Attestation) {
		return nil, false
	}
	return o.Attestation, true
}

// HasAttestation returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) HasAttestation() bool {
	if o != nil && !IsNil(o.Attestation) {
		return true
	}

	return false
}

// SetAttestation gets a reference to the given string and assigns it to the Attestation field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) SetAttestation(v string) {
	o.Attestation = &v
}

// GetExtensions returns the Extensions field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetExtensions() ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions {
	if o == nil || IsNil(o.Extensions) {
		var ret ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions
		return ret
	}
	return *o.Extensions
}

// GetExtensionsOk returns a tuple with the Extensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) GetExtensionsOk() (*ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions, bool) {
	if o == nil || IsNil(o.Extensions) {
		return nil, false
	}
	return o.Extensions, true
}

// HasExtensions returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) HasExtensions() bool {
	if o != nil && !IsNil(o.Extensions) {
		return true
	}

	return false
}

// SetExtensions gets a reference to the given ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions and assigns it to the Extensions field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) SetExtensions(v ApiInteractionVerificationWebauthnRegistrationPost200ResponseExtensions) {
	o.Extensions = &v
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rp"] = o.Rp
	toSerialize["user"] = o.User
	toSerialize["challenge"] = o.Challenge
	toSerialize["pubKeyCredParams"] = o.PubKeyCredParams
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	if !IsNil(o.ExcludeCredentials) {
		toSerialize["excludeCredentials"] = o.ExcludeCredentials
	}
	if !IsNil(o.AuthenticatorSelection) {
		toSerialize["authenticatorSelection"] = o.AuthenticatorSelection
	}
	if !IsNil(o.Attestation) {
		toSerialize["attestation"] = o.Attestation
	}
	if !IsNil(o.Extensions) {
		toSerialize["extensions"] = o.Extensions
	}
	return toSerialize, nil
}

func (o *ApiInteractionVerificationWebauthnRegistrationPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rp",
		"user",
		"challenge",
		"pubKeyCredParams",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiInteractionVerificationWebauthnRegistrationPost200Response := _ApiInteractionVerificationWebauthnRegistrationPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiInteractionVerificationWebauthnRegistrationPost200Response)

	if err != nil {
		return err
	}

	*o = ApiInteractionVerificationWebauthnRegistrationPost200Response(varApiInteractionVerificationWebauthnRegistrationPost200Response)

	return err
}

type NullableApiInteractionVerificationWebauthnRegistrationPost200Response struct {
	value *ApiInteractionVerificationWebauthnRegistrationPost200Response
	isSet bool
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200Response) Get() *ApiInteractionVerificationWebauthnRegistrationPost200Response {
	return v.value
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200Response) Set(val *ApiInteractionVerificationWebauthnRegistrationPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionVerificationWebauthnRegistrationPost200Response(val *ApiInteractionVerificationWebauthnRegistrationPost200Response) *NullableApiInteractionVerificationWebauthnRegistrationPost200Response {
	return &NullableApiInteractionVerificationWebauthnRegistrationPost200Response{value: val, isSet: true}
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

