/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiInteractionSubmitPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionSubmitPost200Response{}

// ApiInteractionSubmitPost200Response struct for ApiInteractionSubmitPost200Response
type ApiInteractionSubmitPost200Response struct {
	RedirectTo string `json:"redirectTo"`
}

type _ApiInteractionSubmitPost200Response ApiInteractionSubmitPost200Response

// NewApiInteractionSubmitPost200Response instantiates a new ApiInteractionSubmitPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionSubmitPost200Response(redirectTo string) *ApiInteractionSubmitPost200Response {
	this := ApiInteractionSubmitPost200Response{}
	this.RedirectTo = redirectTo
	return &this
}

// NewApiInteractionSubmitPost200ResponseWithDefaults instantiates a new ApiInteractionSubmitPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionSubmitPost200ResponseWithDefaults() *ApiInteractionSubmitPost200Response {
	this := ApiInteractionSubmitPost200Response{}
	return &this
}

// GetRedirectTo returns the RedirectTo field value
func (o *ApiInteractionSubmitPost200Response) GetRedirectTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RedirectTo
}

// GetRedirectToOk returns a tuple with the RedirectTo field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionSubmitPost200Response) GetRedirectToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RedirectTo, true
}

// SetRedirectTo sets field value
func (o *ApiInteractionSubmitPost200Response) SetRedirectTo(v string) {
	o.RedirectTo = v
}

func (o ApiInteractionSubmitPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionSubmitPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["redirectTo"] = o.RedirectTo
	return toSerialize, nil
}

func (o *ApiInteractionSubmitPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"redirectTo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiInteractionSubmitPost200Response := _ApiInteractionSubmitPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiInteractionSubmitPost200Response)

	if err != nil {
		return err
	}

	*o = ApiInteractionSubmitPost200Response(varApiInteractionSubmitPost200Response)

	return err
}

type NullableApiInteractionSubmitPost200Response struct {
	value *ApiInteractionSubmitPost200Response
	isSet bool
}

func (v NullableApiInteractionSubmitPost200Response) Get() *ApiInteractionSubmitPost200Response {
	return v.value
}

func (v *NullableApiInteractionSubmitPost200Response) Set(val *ApiInteractionSubmitPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionSubmitPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionSubmitPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionSubmitPost200Response(val *ApiInteractionSubmitPost200Response) *NullableApiInteractionSubmitPost200Response {
	return &NullableApiInteractionSubmitPost200Response{value: val, isSet: true}
}

func (v NullableApiInteractionSubmitPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionSubmitPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

