/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
)

// checks if the ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection{}

// ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection struct for ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection
type ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection struct {
	AuthenticatorAttachment *string `json:"authenticatorAttachment,omitempty"`
	RequireResidentKey *bool `json:"requireResidentKey,omitempty"`
	ResidentKey *string `json:"residentKey,omitempty"`
	UserVerification *string `json:"userVerification,omitempty"`
}

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection() *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection {
	this := ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection{}
	return &this
}

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelectionWithDefaults instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelectionWithDefaults() *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection {
	this := ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection{}
	return &this
}

// GetAuthenticatorAttachment returns the AuthenticatorAttachment field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) GetAuthenticatorAttachment() string {
	if o == nil || IsNil(o.AuthenticatorAttachment) {
		var ret string
		return ret
	}
	return *o.AuthenticatorAttachment
}

// GetAuthenticatorAttachmentOk returns a tuple with the AuthenticatorAttachment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) GetAuthenticatorAttachmentOk() (*string, bool) {
	if o == nil || IsNil(o.AuthenticatorAttachment) {
		return nil, false
	}
	return o.AuthenticatorAttachment, true
}

// HasAuthenticatorAttachment returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) HasAuthenticatorAttachment() bool {
	if o != nil && !IsNil(o.AuthenticatorAttachment) {
		return true
	}

	return false
}

// SetAuthenticatorAttachment gets a reference to the given string and assigns it to the AuthenticatorAttachment field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) SetAuthenticatorAttachment(v string) {
	o.AuthenticatorAttachment = &v
}

// GetRequireResidentKey returns the RequireResidentKey field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) GetRequireResidentKey() bool {
	if o == nil || IsNil(o.RequireResidentKey) {
		var ret bool
		return ret
	}
	return *o.RequireResidentKey
}

// GetRequireResidentKeyOk returns a tuple with the RequireResidentKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) GetRequireResidentKeyOk() (*bool, bool) {
	if o == nil || IsNil(o.RequireResidentKey) {
		return nil, false
	}
	return o.RequireResidentKey, true
}

// HasRequireResidentKey returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) HasRequireResidentKey() bool {
	if o != nil && !IsNil(o.RequireResidentKey) {
		return true
	}

	return false
}

// SetRequireResidentKey gets a reference to the given bool and assigns it to the RequireResidentKey field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) SetRequireResidentKey(v bool) {
	o.RequireResidentKey = &v
}

// GetResidentKey returns the ResidentKey field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) GetResidentKey() string {
	if o == nil || IsNil(o.ResidentKey) {
		var ret string
		return ret
	}
	return *o.ResidentKey
}

// GetResidentKeyOk returns a tuple with the ResidentKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) GetResidentKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ResidentKey) {
		return nil, false
	}
	return o.ResidentKey, true
}

// HasResidentKey returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) HasResidentKey() bool {
	if o != nil && !IsNil(o.ResidentKey) {
		return true
	}

	return false
}

// SetResidentKey gets a reference to the given string and assigns it to the ResidentKey field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) SetResidentKey(v string) {
	o.ResidentKey = &v
}

// GetUserVerification returns the UserVerification field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) GetUserVerification() string {
	if o == nil || IsNil(o.UserVerification) {
		var ret string
		return ret
	}
	return *o.UserVerification
}

// GetUserVerificationOk returns a tuple with the UserVerification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) GetUserVerificationOk() (*string, bool) {
	if o == nil || IsNil(o.UserVerification) {
		return nil, false
	}
	return o.UserVerification, true
}

// HasUserVerification returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) HasUserVerification() bool {
	if o != nil && !IsNil(o.UserVerification) {
		return true
	}

	return false
}

// SetUserVerification gets a reference to the given string and assigns it to the UserVerification field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) SetUserVerification(v string) {
	o.UserVerification = &v
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthenticatorAttachment) {
		toSerialize["authenticatorAttachment"] = o.AuthenticatorAttachment
	}
	if !IsNil(o.RequireResidentKey) {
		toSerialize["requireResidentKey"] = o.RequireResidentKey
	}
	if !IsNil(o.ResidentKey) {
		toSerialize["residentKey"] = o.ResidentKey
	}
	if !IsNil(o.UserVerification) {
		toSerialize["userVerification"] = o.UserVerification
	}
	return toSerialize, nil
}

type NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection struct {
	value *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection
	isSet bool
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) Get() *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection {
	return v.value
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) Set(val *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection(val *ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection {
	return &NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection{value: val, isSet: true}
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

