/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp{}

// ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp struct for ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp
type ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp struct {
	Name string `json:"name"`
	Id *string `json:"id,omitempty"`
}

type _ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponseRp instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponseRp(name string) *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp {
	this := ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp{}
	this.Name = name
	return &this
}

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponseRpWithDefaults instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponseRpWithDefaults() *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp {
	this := ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp{}
	return &this
}

// GetName returns the Name field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) SetName(v string) {
	o.Name = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) SetId(v string) {
	o.Id = &v
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiInteractionVerificationWebauthnRegistrationPost200ResponseRp := _ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiInteractionVerificationWebauthnRegistrationPost200ResponseRp)

	if err != nil {
		return err
	}

	*o = ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp(varApiInteractionVerificationWebauthnRegistrationPost200ResponseRp)

	return err
}

type NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseRp struct {
	value *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp
	isSet bool
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) Get() *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp {
	return v.value
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) Set(val *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionVerificationWebauthnRegistrationPost200ResponseRp(val *ApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseRp {
	return &NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseRp{value: val, isSet: true}
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseRp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

