/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner{}

// ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner struct for ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner
type ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner struct {
	Type string `json:"type"`
	Id string `json:"id"`
	Transports []string `json:"transports,omitempty"`
}

type _ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner(type_ string, id string) *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner {
	this := ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInnerWithDefaults instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInnerWithDefaults() *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner {
	this := ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner{}
	return &this
}

// GetType returns the Type field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) SetId(v string) {
	o.Id = v
}

// GetTransports returns the Transports field value if set, zero value otherwise.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) GetTransports() []string {
	if o == nil || IsNil(o.Transports) {
		var ret []string
		return ret
	}
	return o.Transports
}

// GetTransportsOk returns a tuple with the Transports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) GetTransportsOk() ([]string, bool) {
	if o == nil || IsNil(o.Transports) {
		return nil, false
	}
	return o.Transports, true
}

// HasTransports returns a boolean if a field has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) HasTransports() bool {
	if o != nil && !IsNil(o.Transports) {
		return true
	}

	return false
}

// SetTransports gets a reference to the given []string and assigns it to the Transports field.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) SetTransports(v []string) {
	o.Transports = v
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	if !IsNil(o.Transports) {
		toSerialize["transports"] = o.Transports
	}
	return toSerialize, nil
}

func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner := _ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner)

	if err != nil {
		return err
	}

	*o = ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner(varApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner)

	return err
}

type NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner struct {
	value *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner
	isSet bool
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) Get() *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner {
	return v.value
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) Set(val *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner(val *ApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner {
	return &NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner{value: val, isSet: true}
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseExcludeCredentialsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

