/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner{}

// ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner struct for ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner
type ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Description NullableString `json:"description"`
}

type _ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner

// NewApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner instantiates a new ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner(id string, name string, description NullableString) *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner {
	this := ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner{}
	this.Id = id
	this.Name = name
	this.Description = description
	return &this
}

// NewApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInnerWithDefaults instantiates a new ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInnerWithDefaults() *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner {
	this := ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner{}
	return &this
}

// GetId returns the Id field value
func (o *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) SetDescription(v string) {
	o.Description.Set(&v)
}

func (o ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description.Get()
	return toSerialize, nil
}

func (o *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner := _ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner)

	if err != nil {
		return err
	}

	*o = ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner(varApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner)

	return err
}

type NullableApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner struct {
	value *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner
	isSet bool
}

func (v NullableApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) Get() *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner {
	return v.value
}

func (v *NullableApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) Set(val *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner(val *ApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) *NullableApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner {
	return &NullableApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner{value: val, isSet: true}
}

func (v NullableApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionConsentGet200ResponseOrganizationsInnerMissingResourceScopesInnerScopesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

