/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser{}

// ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser struct for ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser
type ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser struct {
	Id string `json:"id"`
	Name string `json:"name"`
	DisplayName string `json:"displayName"`
}

type _ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponseUser instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponseUser(id string, name string, displayName string) *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser {
	this := ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser{}
	this.Id = id
	this.Name = name
	this.DisplayName = displayName
	return &this
}

// NewApiInteractionVerificationWebauthnRegistrationPost200ResponseUserWithDefaults instantiates a new ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionVerificationWebauthnRegistrationPost200ResponseUserWithDefaults() *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser {
	this := ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser{}
	return &this
}

// GetId returns the Id field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) SetDisplayName(v string) {
	o.DisplayName = v
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	return toSerialize, nil
}

func (o *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"displayName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiInteractionVerificationWebauthnRegistrationPost200ResponseUser := _ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiInteractionVerificationWebauthnRegistrationPost200ResponseUser)

	if err != nil {
		return err
	}

	*o = ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser(varApiInteractionVerificationWebauthnRegistrationPost200ResponseUser)

	return err
}

type NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseUser struct {
	value *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser
	isSet bool
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) Get() *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser {
	return v.value
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) Set(val *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionVerificationWebauthnRegistrationPost200ResponseUser(val *ApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseUser {
	return &NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseUser{value: val, isSet: true}
}

func (v NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionVerificationWebauthnRegistrationPost200ResponseUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

