/*
Logto API references

API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.

API version: Cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logto

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiInteractionMfaPutRequestOneOfResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInteractionMfaPutRequestOneOfResponse{}

// ApiInteractionMfaPutRequestOneOfResponse struct for ApiInteractionMfaPutRequestOneOfResponse
type ApiInteractionMfaPutRequestOneOfResponse struct {
	ClientDataJSON string `json:"clientDataJSON"`
	AuthenticatorData string `json:"authenticatorData"`
	Signature string `json:"signature"`
	UserHandle *string `json:"userHandle,omitempty"`
}

type _ApiInteractionMfaPutRequestOneOfResponse ApiInteractionMfaPutRequestOneOfResponse

// NewApiInteractionMfaPutRequestOneOfResponse instantiates a new ApiInteractionMfaPutRequestOneOfResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInteractionMfaPutRequestOneOfResponse(clientDataJSON string, authenticatorData string, signature string) *ApiInteractionMfaPutRequestOneOfResponse {
	this := ApiInteractionMfaPutRequestOneOfResponse{}
	this.ClientDataJSON = clientDataJSON
	this.AuthenticatorData = authenticatorData
	this.Signature = signature
	return &this
}

// NewApiInteractionMfaPutRequestOneOfResponseWithDefaults instantiates a new ApiInteractionMfaPutRequestOneOfResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInteractionMfaPutRequestOneOfResponseWithDefaults() *ApiInteractionMfaPutRequestOneOfResponse {
	this := ApiInteractionMfaPutRequestOneOfResponse{}
	return &this
}

// GetClientDataJSON returns the ClientDataJSON field value
func (o *ApiInteractionMfaPutRequestOneOfResponse) GetClientDataJSON() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientDataJSON
}

// GetClientDataJSONOk returns a tuple with the ClientDataJSON field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionMfaPutRequestOneOfResponse) GetClientDataJSONOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientDataJSON, true
}

// SetClientDataJSON sets field value
func (o *ApiInteractionMfaPutRequestOneOfResponse) SetClientDataJSON(v string) {
	o.ClientDataJSON = v
}

// GetAuthenticatorData returns the AuthenticatorData field value
func (o *ApiInteractionMfaPutRequestOneOfResponse) GetAuthenticatorData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthenticatorData
}

// GetAuthenticatorDataOk returns a tuple with the AuthenticatorData field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionMfaPutRequestOneOfResponse) GetAuthenticatorDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticatorData, true
}

// SetAuthenticatorData sets field value
func (o *ApiInteractionMfaPutRequestOneOfResponse) SetAuthenticatorData(v string) {
	o.AuthenticatorData = v
}

// GetSignature returns the Signature field value
func (o *ApiInteractionMfaPutRequestOneOfResponse) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *ApiInteractionMfaPutRequestOneOfResponse) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *ApiInteractionMfaPutRequestOneOfResponse) SetSignature(v string) {
	o.Signature = v
}

// GetUserHandle returns the UserHandle field value if set, zero value otherwise.
func (o *ApiInteractionMfaPutRequestOneOfResponse) GetUserHandle() string {
	if o == nil || IsNil(o.UserHandle) {
		var ret string
		return ret
	}
	return *o.UserHandle
}

// GetUserHandleOk returns a tuple with the UserHandle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInteractionMfaPutRequestOneOfResponse) GetUserHandleOk() (*string, bool) {
	if o == nil || IsNil(o.UserHandle) {
		return nil, false
	}
	return o.UserHandle, true
}

// HasUserHandle returns a boolean if a field has been set.
func (o *ApiInteractionMfaPutRequestOneOfResponse) HasUserHandle() bool {
	if o != nil && !IsNil(o.UserHandle) {
		return true
	}

	return false
}

// SetUserHandle gets a reference to the given string and assigns it to the UserHandle field.
func (o *ApiInteractionMfaPutRequestOneOfResponse) SetUserHandle(v string) {
	o.UserHandle = &v
}

func (o ApiInteractionMfaPutRequestOneOfResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInteractionMfaPutRequestOneOfResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clientDataJSON"] = o.ClientDataJSON
	toSerialize["authenticatorData"] = o.AuthenticatorData
	toSerialize["signature"] = o.Signature
	if !IsNil(o.UserHandle) {
		toSerialize["userHandle"] = o.UserHandle
	}
	return toSerialize, nil
}

func (o *ApiInteractionMfaPutRequestOneOfResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"clientDataJSON",
		"authenticatorData",
		"signature",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiInteractionMfaPutRequestOneOfResponse := _ApiInteractionMfaPutRequestOneOfResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiInteractionMfaPutRequestOneOfResponse)

	if err != nil {
		return err
	}

	*o = ApiInteractionMfaPutRequestOneOfResponse(varApiInteractionMfaPutRequestOneOfResponse)

	return err
}

type NullableApiInteractionMfaPutRequestOneOfResponse struct {
	value *ApiInteractionMfaPutRequestOneOfResponse
	isSet bool
}

func (v NullableApiInteractionMfaPutRequestOneOfResponse) Get() *ApiInteractionMfaPutRequestOneOfResponse {
	return v.value
}

func (v *NullableApiInteractionMfaPutRequestOneOfResponse) Set(val *ApiInteractionMfaPutRequestOneOfResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInteractionMfaPutRequestOneOfResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInteractionMfaPutRequestOneOfResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInteractionMfaPutRequestOneOfResponse(val *ApiInteractionMfaPutRequestOneOfResponse) *NullableApiInteractionMfaPutRequestOneOfResponse {
	return &NullableApiInteractionMfaPutRequestOneOfResponse{value: val, isSet: true}
}

func (v NullableApiInteractionMfaPutRequestOneOfResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInteractionMfaPutRequestOneOfResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

